/* Auto-generated by tools/build_manifest.py — do not edit */
#ifndef POKEYELLOW_ASSETS_MANIFEST_H
#define POKEYELLOW_ASSETS_MANIFEST_H

#include <stddef.h>
#include <stdint.h>

#include "gb_asset_loader.h"

#define POKEYELLOW_ASSETS_MANIFEST_COUNT 145

static const GBAssetEntry POKEYELLOW_ASSETS_MANIFEST[POKEYELLOW_ASSETS_MANIFEST_COUNT] = {
    { 0x00000000, 0x00000008, "code/rst0.bin" }, /* rst0 bank 00 */
    { 0x00000008, 0x00000008, "code/rst8.bin" }, /* rst8 bank 00 */
    { 0x00000010, 0x00000008, "code/rst10.bin" }, /* rst10 bank 00 */
    { 0x00000018, 0x00000008, "code/rst18.bin" }, /* rst18 bank 00 */
    { 0x00000020, 0x00000008, "code/rst20.bin" }, /* rst20 bank 00 */
    { 0x00000028, 0x00000008, "code/rst28.bin" }, /* rst28 bank 00 */
    { 0x00000030, 0x00000008, "code/rst30.bin" }, /* rst30 bank 00 */
    { 0x00000038, 0x00000008, "code/rst38.bin" }, /* rst38 bank 00 */
    { 0x00000040, 0x00000008, "code/vblank.bin" }, /* vblank bank 00 */
    { 0x00000048, 0x00000008, "code/lcd.bin" }, /* lcd bank 00 */
    { 0x00000050, 0x00000008, "code/timer.bin" }, /* timer bank 00 */
    { 0x00000058, 0x00000008, "code/serial.bin" }, /* serial bank 00 */
    { 0x00000060, 0x00000001, "code/joypad.bin" }, /* joypad bank 00 */
    { 0x00000061, 0x0000009b, "code/high_home.bin" }, /* High Home bank 00 */
    { 0x00000100, 0x00000050, "code/header.bin" }, /* Header bank 00 */
    { 0x00000150, 0x00003e9f, "code/home.bin" }, /* Home bank 00 */
    { 0x00004000, 0x00003af0, "code/bank1.bin" }, /* bank1 bank 01 */
    { 0x00008000, 0x0000022e, "audio/sound_effect_headers_1.bin" }, /* Sound Effect Headers 1 bank 02 */
    { 0x0000822e, 0x000000cf, "audio/music_headers_1.bin" }, /* Music Headers 1 bank 02 */
    { 0x000082fd, 0x00000d67, "audio/sound_effects_1.bin" }, /* Sound Effects 1 bank 02 */
    { 0x00009064, 0x000009b2, "audio/audio_engine_1.bin" }, /* Audio Engine 1 bank 02 */
    { 0x00009a16, 0x000024b1, "audio/music_1.bin" }, /* Music 1 bank 02 */
    { 0x0000c000, 0x00003ad8, "code/bank3.bin" }, /* bank3 bank 03 */
    { 0x00010000, 0x00002365, "code/bank4.bin" }, /* bank4 bank 04 */
    { 0x00012365, 0x00001400, "gfx/npc_sprites_1.bin" }, /* NPC Sprites 1 bank 04 */
    { 0x00013765, 0x000002bd, "battle/battle_engine_1.bin" }, /* Battle Engine 1 bank 04 */
    { 0x00014000, 0x000003f1, "code/bank5.bin" }, /* bank5 bank 05 */
    { 0x000143f1, 0x00003840, "gfx/npc_sprites_2.bin" }, /* NPC Sprites 2 bank 05 */
    { 0x00017c31, 0x000001b2, "battle/battle_engine_2.bin" }, /* Battle Engine 2 bank 05 */
    { 0x00018000, 0x00000dfa, "maps/maps_1.bin" }, /* Maps 1 bank 06 */
    { 0x00018dfa, 0x000016f0, "maps/maps_2.bin" }, /* Maps 2 bank 06 */
    { 0x0001a4ea, 0x000003b9, "maps/doors_and_ledges.bin" }, /* Doors and Ledges bank 06 */
    { 0x0001c000, 0x0000021e, "maps/maps_3.bin" }, /* Maps 3 bank 07 */
    { 0x0001c21e, 0x000000a4, "code/bank7.bin" }, /* bank7 bank 07 */
    { 0x0001c2c2, 0x00001fec, "maps/maps_4.bin" }, /* Maps 4 bank 07 */
    { 0x0001e2ae, 0x000003ea, "maps/hidden_events_1.bin" }, /* Hidden Events 1 bank 07 */
    { 0x00020000, 0x000002be, "audio/sound_effect_headers_2.bin" }, /* Sound Effect Headers 2 bank 08 */
    { 0x000202be, 0x0000003f, "audio/music_headers_2.bin" }, /* Music Headers 2 bank 08 */
    { 0x000202fd, 0x00001021, "audio/sound_effects_2.bin" }, /* Sound Effects 2 bank 08 */
    { 0x0002131e, 0x0000005a, "audio/low_health_alarm_audio_engine_2.bin" }, /* Low Health Alarm (Audio Engine 2) bank 08 */
    { 0x00021378, 0x00000543, "data/bill_s_pc.bin" }, /* Bill's PC bank 08 */
    { 0x000218bb, 0x000002df, "audio/audio_engine_2.bin" }, /* Audio Engine 2 bank 08 */
    { 0x00021b9a, 0x00001c23, "audio/music_2.bin" }, /* Music 2 bank 08 */
    { 0x00024000, 0x00003d20, "gfx/pics_1.bin" }, /* Pics 1 bank 09 */
    { 0x00027d20, 0x0000021b, "battle/battle_engine_3.bin" }, /* Battle Engine 3 bank 09 */
    { 0x00028000, 0x00003d4c, "gfx/pics_2.bin" }, /* Pics 2 bank 0a */
    { 0x0002bd4c, 0x000000c1, "battle/battle_engine_4.bin" }, /* Battle Engine 4 bank 0a */
    { 0x0002c000, 0x00003d25, "gfx/pics_3.bin" }, /* Pics 3 bank 0b */
    { 0x0002fd25, 0x0000010b, "battle/battle_engine_5.bin" }, /* Battle Engine 5 bank 0b */
    { 0x00030000, 0x00003d55, "gfx/pics_4.bin" }, /* Pics 4 bank 0c */
    { 0x00034000, 0x0000349e, "gfx/pics_5.bin" }, /* Pics 5 bank 0d */
    { 0x0003749e, 0x00000a8e, "data/slot_machines.bin" }, /* Slot Machines bank 0d */
    { 0x00038000, 0x00003bab, "battle/battle_engine_6.bin" }, /* Battle Engine 6 bank 0e */
    { 0x0003c000, 0x00003bab, "battle/battle_core.bin" }, /* Battle Core bank 0f */
    { 0x00040000, 0x00001f7a, "code/bank10.bin" }, /* bank10 bank 10 */
    { 0x00044000, 0x00000169, "maps/maps_5.bin" }, /* Maps 5 bank 11 */
    { 0x00044169, 0x000000e8, "text/pok_dex_rating.bin" }, /* Pokédex Rating bank 11 */
    { 0x00044251, 0x000029a2, "maps/maps_6.bin" }, /* Maps 6 bank 11 */
    { 0x00046bf3, 0x0000001f, "data/dungeon_warps.bin" }, /* Dungeon Warps bank 11 */
    { 0x00048000, 0x000000eb, "maps/maps_7.bin" }, /* Maps 7 bank 12 */
    { 0x000480eb, 0x00002455, "maps/maps_8.bin" }, /* Maps 8 bank 12 */
    { 0x0004c000, 0x00003e79, "gfx/trainer_pics.bin" }, /* Trainer Pics bank 13 */
    { 0x0004fe79, 0x000000a1, "maps/maps_9.bin" }, /* Maps 9 bank 13 */
    { 0x00050000, 0x000025d8, "maps/maps_10.bin" }, /* Maps 10 bank 14 */
    { 0x000525d8, 0x000003ca, "maps/hidden_events_2.bin" }, /* Hidden Events 2 bank 14 */
    { 0x00054000, 0x0000125f, "maps/maps_11.bin" }, /* Maps 11 bank 15 */
    { 0x0005525f, 0x00000298, "battle/battle_engine_7.bin" }, /* Battle Engine 7 bank 15 */
    { 0x000554f7, 0x0000121d, "maps/maps_12.bin" }, /* Maps 12 bank 15 */
    { 0x00056714, 0x00000031, "data/diploma.bin" }, /* Diploma bank 15 */
    { 0x00056745, 0x00000252, "data/trainer_sight.bin" }, /* Trainer Sight bank 15 */
    { 0x00058000, 0x00000d99, "maps/maps_13.bin" }, /* Maps 13 bank 16 */
    { 0x00058d99, 0x000001ae, "code/bank16.bin" }, /* bank16 bank 16 */
    { 0x00058f47, 0x000015f3, "maps/maps_14.bin" }, /* Maps 14 bank 16 */
    { 0x0005a53a, 0x0000001c, "data/saffron_guards.bin" }, /* Saffron Guards bank 16 */
    { 0x0005c000, 0x000000d4, "maps/maps_15.bin" }, /* Maps 15 bank 17 */
    { 0x0005c0d4, 0x0000000f, "text/starter_dex.bin" }, /* Starter Dex bank 17 */
    { 0x0005c0e3, 0x0000198d, "maps/maps_16.bin" }, /* Maps 16 bank 17 */
    { 0x0005da70, 0x000004f0, "maps/hidden_events_3.bin" }, /* Hidden Events 3 bank 17 */
    { 0x00060000, 0x00000ff2, "maps/maps_17.bin" }, /* Maps 17 bank 18 */
    { 0x00060ff2, 0x000000fb, "data/cinnabar_lab_fossils.bin" }, /* Cinnabar Lab Fossils bank 18 */
    { 0x000610ed, 0x000014fb, "maps/maps_18.bin" }, /* Maps 18 bank 18 */
    { 0x000625e8, 0x0000011a, "maps/hidden_events_4.bin" }, /* Hidden Events 4 bank 18 */
    { 0x00064000, 0x00004000, "gfx/tilesets_1.bin" }, /* Tilesets 1 bank 19 */
    { 0x00068000, 0x00000040, "data/version_graphics.bin" }, /* Version Graphics bank 1a */
    { 0x00068040, 0x00003fb0, "gfx/tilesets_2.bin" }, /* Tilesets 2 bank 1a */
    { 0x0006c000, 0x00004000, "gfx/tilesets_3.bin" }, /* Tilesets 3 bank 1b */
    { 0x00070000, 0x00003eb3, "code/bank1c.bin" }, /* bank1C bank 1c */
    { 0x00074000, 0x0000005c, "maps/maps_19.bin" }, /* Maps 19 bank 1d */
    { 0x0007405c, 0x00000053, "data/itemfinder_1.bin" }, /* Itemfinder 1 bank 1d */
    { 0x000740af, 0x00000677, "maps/maps_20.bin" }, /* Maps 20 bank 1d */
    { 0x00074726, 0x0000012b, "data/vending_machine.bin" }, /* Vending Machine bank 1d */
    { 0x00074851, 0x000015ad, "maps/maps_21.bin" }, /* Maps 21 bank 1d */
    { 0x00075dfe, 0x00000379, "data/itemfinder_2.bin" }, /* Itemfinder 2 bank 1d */
    { 0x00078000, 0x00003f91, "code/bank1e.bin" }, /* bank1E bank 1e */
    { 0x0007c000, 0x00000249, "audio/sound_effect_headers_3.bin" }, /* Sound Effect Headers 3 bank 1f */
    { 0x0007c249, 0x000000b1, "audio/music_headers_3.bin" }, /* Music Headers 3 bank 1f */
    { 0x0007c2fa, 0x00000ddc, "audio/sound_effects_3.bin" }, /* Sound Effects 3 bank 1f */
    { 0x0007d0d6, 0x0000014b, "audio/audio_engine_3.bin" }, /* Audio Engine 3 bank 1f */
    { 0x0007d221, 0x0000263f, "audio/music_3.bin" }, /* Music 3 bank 1f */
    { 0x00080000, 0x000001cb, "audio/sound_effect_headers_4.bin" }, /* Sound Effect Headers 4 bank 20 */
    { 0x000801cb, 0x00000021, "audio/music_headers_4.bin" }, /* Music Headers 4 bank 20 */
    { 0x000801ec, 0x00000d28, "audio/sound_effects_4.bin" }, /* Sound Effects 4 bank 20 */
    { 0x00080f14, 0x00001cc0, "data/surfing_pikachu_graphics.bin" }, /* Surfing Pikachu Graphics bank 20 */
    { 0x00082bd4, 0x00000114, "audio/audio_engine_4.bin" }, /* Audio Engine 4 bank 20 */
    { 0x00082ce8, 0x00001318, "audio/music_4.bin" }, /* Music 4 bank 20 */
    { 0x00084000, 0x000029e8, "data/pikachu_cries_1.bin" }, /* Pikachu Cries 1 bank 21 */
    { 0x00088000, 0x00002ffe, "data/pikachu_cries_2.bin" }, /* Pikachu Cries 2 bank 22 */
    { 0x0008c000, 0x00003e0e, "data/pikachu_cries_3.bin" }, /* Pikachu Cries 3 bank 23 */
    { 0x00090000, 0x00002826, "data/pikachu_cries_4.bin" }, /* Pikachu Cries 4 bank 24 */
    { 0x00094000, 0x00002d1c, "data/pikachu_cries_5.bin" }, /* Pikachu Cries 5 bank 25 */
    { 0x00098000, 0x00003acb, "text/text_1.bin" }, /* Text 1 bank 26 */
    { 0x0009c000, 0x00003b97, "text/text_2.bin" }, /* Text 2 bank 27 */
    { 0x000a0000, 0x00003c44, "text/text_3.bin" }, /* Text 3 bank 28 */
    { 0x000a4000, 0x00003728, "text/text_4.bin" }, /* Text 4 bank 29 */
    { 0x000a8000, 0x00003b86, "text/text_5.bin" }, /* Text 5 bank 2a */
    { 0x000ac000, 0x00003a02, "text/text_6.bin" }, /* Text 6 bank 2b */
    { 0x000b0000, 0x000038f0, "text/text_7.bin" }, /* Text 7 bank 2c */
    { 0x000b4000, 0x0000319e, "text/text_8.bin" }, /* Text 8 bank 2d */
    { 0x000b8000, 0x000039a2, "text/pok_dex_text.bin" }, /* Pokédex Text bank 2e */
    { 0x000bc000, 0x0000060f, "text/move_names.bin" }, /* Move Names bank 2f */
    { 0x000bd000, 0x00002585, "data/bg_map_attributes.bin" }, /* BG Map Attributes bank 2f */
    { 0x000c0000, 0x00004000, "code/bank30.bin" }, /* bank30 bank 30 */
    { 0x000c4000, 0x00003cc6, "data/pikachu_cries_6.bin" }, /* Pikachu Cries 6 bank 31 */
    { 0x000c8000, 0x00004000, "data/pikachu_cries_7.bin" }, /* Pikachu Cries 7 bank 32 */
    { 0x000cc000, 0x00003ff6, "data/pikachu_cries_8.bin" }, /* Pikachu Cries 8 bank 33 */
    { 0x000d0000, 0x00002576, "data/pikachu_cries_9.bin" }, /* Pikachu Cries 9 bank 34 */
    { 0x000d4000, 0x00003602, "data/pikachu_cries_10.bin" }, /* Pikachu Cries 10 bank 35 */
    { 0x000d8000, 0x00003f60, "data/pikachu_cries_11.bin" }, /* Pikachu Cries 11 bank 36 */
    { 0x000dc000, 0x00003f96, "data/pikachu_cries_12.bin" }, /* Pikachu Cries 12 bank 37 */
    { 0x000e0000, 0x00003ef8, "data/pikachu_cries_13.bin" }, /* Pikachu Cries 13 bank 38 */
    { 0x000e4000, 0x00003ea3, "data/pikachu_graphics_1.bin" }, /* Pikachu Graphics 1 bank 39 */
    { 0x000e8000, 0x00002a24, "code/bank3a.bin" }, /* bank3A bank 3a */
    { 0x000f0000, 0x00000314, "data/pikachu_pcm.bin" }, /* Pikachu PCM bank 3c */
    { 0x000f0314, 0x00000740, "gfx/tilesets_4.bin" }, /* Tilesets 4 bank 3c */
    { 0x000f0a54, 0x0000006b, "data/try_pikachu_movement.bin" }, /* Try Pikachu Movement bank 3c */
    { 0x000f0abf, 0x00000453, "data/pikachu_graphics_2.bin" }, /* Pikachu Graphics 2 bank 3c */
    { 0x000f0f12, 0x000009a9, "data/credits.bin" }, /* Credits bank 3c */
    { 0x000f18bb, 0x00000d3d, "maps/maps_22.bin" }, /* Maps 22 bank 3c */
    { 0x000f25f8, 0x000007c0, "maps/hidden_events_core.bin" }, /* Hidden Events Core bank 3c */
    { 0x000f4000, 0x000003b1, "battle/battle_engine_8.bin" }, /* Battle Engine 8 bank 3d */
    { 0x000f43b1, 0x0000018e, "gfx/pics_7.bin" }, /* Pics 7 bank 3d */
    { 0x000f453f, 0x00002407, "battle/battle_engine_9.bin" }, /* Battle Engine 9 bank 3d */
    { 0x000f8000, 0x00003d76, "data/surfing_minigame.bin" }, /* Surfing Minigame bank 3e */
    { 0x000fc000, 0x0000266f, "data/overworld_pikachu.bin" }, /* Overworld Pikachu bank 3f */
    { 0x000fe66f, 0x00000c00, "gfx/npc_sprites_3.bin" }, /* NPC Sprites 3 bank 3f */
};

#endif
