#pragma once
#include <array>

// Map IDs from pret/pokeyellow constants/map_constants.asm (UE Yellow).
// Names only; graphics and map layouts are always read from the user ROM.
namespace kanto {
inline constexpr std::array<const char *, 249> MapNames = {{
    "PALLET_TOWN",                   // 0
    "VIRIDIAN_CITY",                 // 1
    "PEWTER_CITY",                   // 2
    "CERULEAN_CITY",                 // 3
    "LAVENDER_TOWN",                 // 4
    "VERMILION_CITY",                // 5
    "CELADON_CITY",                  // 6
    "FUCHSIA_CITY",                  // 7
    "CINNABAR_ISLAND",               // 8
    "INDIGO_PLATEAU",                // 9
    "SAFFRON_CITY",                  // 10
    "UNUSED_MAP_0B",                 // 11
    "ROUTE_1",                       // 12
    "ROUTE_2",                       // 13
    "ROUTE_3",                       // 14
    "ROUTE_4",                       // 15
    "ROUTE_5",                       // 16
    "ROUTE_6",                       // 17
    "ROUTE_7",                       // 18
    "ROUTE_8",                       // 19
    "ROUTE_9",                       // 20
    "ROUTE_10",                      // 21
    "ROUTE_11",                      // 22
    "ROUTE_12",                      // 23
    "ROUTE_13",                      // 24
    "ROUTE_14",                      // 25
    "ROUTE_15",                      // 26
    "ROUTE_16",                      // 27
    "ROUTE_17",                      // 28
    "ROUTE_18",                      // 29
    "ROUTE_19",                      // 30
    "ROUTE_20",                      // 31
    "ROUTE_21",                      // 32
    "ROUTE_22",                      // 33
    "ROUTE_23",                      // 34
    "ROUTE_24",                      // 35
    "ROUTE_25",                      // 36
    "REDS_HOUSE_1F",                 // 37
    "REDS_HOUSE_2F",                 // 38
    "BLUES_HOUSE",                   // 39
    "OAKS_LAB",                      // 40
    "VIRIDIAN_POKECENTER",           // 41
    "VIRIDIAN_MART",                 // 42
    "VIRIDIAN_SCHOOL_HOUSE",         // 43
    "VIRIDIAN_NICKNAME_HOUSE",       // 44
    "VIRIDIAN_GYM",                  // 45
    "DIGLETTS_CAVE_ROUTE_2",         // 46
    "VIRIDIAN_FOREST_NORTH_GATE",    // 47
    "ROUTE_2_TRADE_HOUSE",           // 48
    "ROUTE_2_GATE",                  // 49
    "VIRIDIAN_FOREST_SOUTH_GATE",    // 50
    "VIRIDIAN_FOREST",               // 51
    "MUSEUM_1F",                     // 52
    "MUSEUM_2F",                     // 53
    "PEWTER_GYM",                    // 54
    "PEWTER_NIDORAN_HOUSE",          // 55
    "PEWTER_MART",                   // 56
    "PEWTER_SPEECH_HOUSE",           // 57
    "PEWTER_POKECENTER",             // 58
    "MT_MOON_1F",                    // 59
    "MT_MOON_B1F",                   // 60
    "MT_MOON_B2F",                   // 61
    "CERULEAN_TRASHED_HOUSE",        // 62
    "CERULEAN_MELANIES_HOUSE",       // 63
    "CERULEAN_POKECENTER",           // 64
    "CERULEAN_GYM",                  // 65
    "BIKE_SHOP",                     // 66
    "CERULEAN_MART",                 // 67
    "MT_MOON_POKECENTER",            // 68
    "CERULEAN_TRASHED_HOUSE_COPY",   // 69
    "ROUTE_5_GATE",                  // 70
    "UNDERGROUND_PATH_ROUTE_5",      // 71
    "DAYCARE",                       // 72
    "ROUTE_6_GATE",                  // 73
    "UNDERGROUND_PATH_ROUTE_6",      // 74
    "UNDERGROUND_PATH_ROUTE_6_COPY", // 75
    "ROUTE_7_GATE",                  // 76
    "UNDERGROUND_PATH_ROUTE_7",      // 77
    "UNDERGROUND_PATH_ROUTE_7_COPY", // 78
    "ROUTE_8_GATE",                  // 79
    "UNDERGROUND_PATH_ROUTE_8",      // 80
    "ROCK_TUNNEL_POKECENTER",        // 81
    "ROCK_TUNNEL_1F",                // 82
    "POWER_PLANT",                   // 83
    "ROUTE_11_GATE_1F",              // 84
    "DIGLETTS_CAVE_ROUTE_11",        // 85
    "ROUTE_11_GATE_2F",              // 86
    "ROUTE_12_GATE_1F",              // 87
    "BILLS_HOUSE",                   // 88
    "VERMILION_POKECENTER",          // 89
    "POKEMON_FAN_CLUB",              // 90
    "VERMILION_MART",                // 91
    "VERMILION_GYM",                 // 92
    "VERMILION_PIDGEY_HOUSE",        // 93
    "VERMILION_DOCK",                // 94
    "SS_ANNE_1F",                    // 95
    "SS_ANNE_2F",                    // 96
    "SS_ANNE_3F",                    // 97
    "SS_ANNE_B1F",                   // 98
    "SS_ANNE_BOW",                   // 99
    "SS_ANNE_KITCHEN",               // 100
    "SS_ANNE_CAPTAINS_ROOM",         // 101
    "SS_ANNE_1F_ROOMS",              // 102
    "SS_ANNE_2F_ROOMS",              // 103
    "SS_ANNE_B1F_ROOMS",             // 104
    "UNUSED_MAP_69",                 // 105
    "UNUSED_MAP_6A",                 // 106
    "UNUSED_MAP_6B",                 // 107
    "VICTORY_ROAD_1F",               // 108
    "UNUSED_MAP_6D",                 // 109
    "UNUSED_MAP_6E",                 // 110
    "UNUSED_MAP_6F",                 // 111
    "UNUSED_MAP_70",                 // 112
    "LANCES_ROOM",                   // 113
    "UNUSED_MAP_72",                 // 114
    "UNUSED_MAP_73",                 // 115
    "UNUSED_MAP_74",                 // 116
    "UNUSED_MAP_75",                 // 117
    "HALL_OF_FAME",                  // 118
    "UNDERGROUND_PATH_NORTH_SOUTH",  // 119
    "CHAMPIONS_ROOM",                // 120
    "UNDERGROUND_PATH_WEST_EAST",    // 121
    "CELADON_MART_1F",               // 122
    "CELADON_MART_2F",               // 123
    "CELADON_MART_3F",               // 124
    "CELADON_MART_4F",               // 125
    "CELADON_MART_ROOF",             // 126
    "CELADON_MART_ELEVATOR",         // 127
    "CELADON_MANSION_1F",            // 128
    "CELADON_MANSION_2F",            // 129
    "CELADON_MANSION_3F",            // 130
    "CELADON_MANSION_ROOF",          // 131
    "CELADON_MANSION_ROOF_HOUSE",    // 132
    "CELADON_POKECENTER",            // 133
    "CELADON_GYM",                   // 134
    "GAME_CORNER",                   // 135
    "CELADON_MART_5F",               // 136
    "GAME_CORNER_PRIZE_ROOM",        // 137
    "CELADON_DINER",                 // 138
    "CELADON_CHIEF_HOUSE",           // 139
    "CELADON_HOTEL",                 // 140
    "LAVENDER_POKECENTER",           // 141
    "POKEMON_TOWER_1F",              // 142
    "POKEMON_TOWER_2F",              // 143
    "POKEMON_TOWER_3F",              // 144
    "POKEMON_TOWER_4F",              // 145
    "POKEMON_TOWER_5F",              // 146
    "POKEMON_TOWER_6F",              // 147
    "POKEMON_TOWER_7F",              // 148
    "MR_FUJIS_HOUSE",                // 149
    "LAVENDER_MART",                 // 150
    "LAVENDER_CUBONE_HOUSE",         // 151
    "FUCHSIA_MART",                  // 152
    "FUCHSIA_BILLS_GRANDPAS_HOUSE",  // 153
    "FUCHSIA_POKECENTER",            // 154
    "WARDENS_HOUSE",                 // 155
    "SAFARI_ZONE_GATE",              // 156
    "FUCHSIA_GYM",                   // 157
    "FUCHSIA_MEETING_ROOM",          // 158
    "SEAFOAM_ISLANDS_B1F",           // 159
    "SEAFOAM_ISLANDS_B2F",           // 160
    "SEAFOAM_ISLANDS_B3F",           // 161
    "SEAFOAM_ISLANDS_B4F",           // 162
    "VERMILION_OLD_ROD_HOUSE",       // 163
    "FUCHSIA_GOOD_ROD_HOUSE",        // 164
    "POKEMON_MANSION_1F",            // 165
    "CINNABAR_GYM",                  // 166
    "CINNABAR_LAB",                  // 167
    "CINNABAR_LAB_TRADE_ROOM",       // 168
    "CINNABAR_LAB_METRONOME_ROOM",   // 169
    "CINNABAR_LAB_FOSSIL_ROOM",      // 170
    "CINNABAR_POKECENTER",           // 171
    "CINNABAR_MART",                 // 172
    "CINNABAR_MART_COPY",            // 173
    "INDIGO_PLATEAU_LOBBY",          // 174
    "COPYCATS_HOUSE_1F",             // 175
    "COPYCATS_HOUSE_2F",             // 176
    "FIGHTING_DOJO",                 // 177
    "SAFFRON_GYM",                   // 178
    "SAFFRON_PIDGEY_HOUSE",          // 179
    "SAFFRON_MART",                  // 180
    "SILPH_CO_1F",                   // 181
    "SAFFRON_POKECENTER",            // 182
    "MR_PSYCHICS_HOUSE",             // 183
    "ROUTE_15_GATE_1F",              // 184
    "ROUTE_15_GATE_2F",              // 185
    "ROUTE_16_GATE_1F",              // 186
    "ROUTE_16_GATE_2F",              // 187
    "ROUTE_16_FLY_HOUSE",            // 188
    "ROUTE_12_SUPER_ROD_HOUSE",      // 189
    "ROUTE_18_GATE_1F",              // 190
    "ROUTE_18_GATE_2F",              // 191
    "SEAFOAM_ISLANDS_1F",            // 192
    "ROUTE_22_GATE",                 // 193
    "VICTORY_ROAD_2F",               // 194
    "ROUTE_12_GATE_2F",              // 195
    "VERMILION_TRADE_HOUSE",         // 196
    "DIGLETTS_CAVE",                 // 197
    "VICTORY_ROAD_3F",               // 198
    "ROCKET_HIDEOUT_B1F",            // 199
    "ROCKET_HIDEOUT_B2F",            // 200
    "ROCKET_HIDEOUT_B3F",            // 201
    "ROCKET_HIDEOUT_B4F",            // 202
    "ROCKET_HIDEOUT_ELEVATOR",       // 203
    "UNUSED_MAP_CC",                 // 204
    "UNUSED_MAP_CD",                 // 205
    "UNUSED_MAP_CE",                 // 206
    "SILPH_CO_2F",                   // 207
    "SILPH_CO_3F",                   // 208
    "SILPH_CO_4F",                   // 209
    "SILPH_CO_5F",                   // 210
    "SILPH_CO_6F",                   // 211
    "SILPH_CO_7F",                   // 212
    "SILPH_CO_8F",                   // 213
    "POKEMON_MANSION_2F",            // 214
    "POKEMON_MANSION_3F",            // 215
    "POKEMON_MANSION_B1F",           // 216
    "SAFARI_ZONE_EAST",              // 217
    "SAFARI_ZONE_NORTH",             // 218
    "SAFARI_ZONE_WEST",              // 219
    "SAFARI_ZONE_CENTER",            // 220
    "SAFARI_ZONE_CENTER_REST_HOUSE", // 221
    "SAFARI_ZONE_SECRET_HOUSE",      // 222
    "SAFARI_ZONE_WEST_REST_HOUSE",   // 223
    "SAFARI_ZONE_EAST_REST_HOUSE",   // 224
    "SAFARI_ZONE_NORTH_REST_HOUSE",  // 225
    "CERULEAN_CAVE_2F",              // 226
    "CERULEAN_CAVE_B1F",             // 227
    "CERULEAN_CAVE_1F",              // 228
    "NAME_RATERS_HOUSE",             // 229
    "CERULEAN_BADGE_HOUSE",          // 230
    "UNUSED_MAP_E7",                 // 231
    "ROCK_TUNNEL_B1F",               // 232
    "SILPH_CO_9F",                   // 233
    "SILPH_CO_10F",                  // 234
    "SILPH_CO_11F",                  // 235
    "SILPH_CO_ELEVATOR",             // 236
    "UNUSED_MAP_ED",                 // 237
    "UNUSED_MAP_EE",                 // 238
    "TRADE_CENTER",                  // 239
    "COLOSSEUM",                     // 240
    "UNUSED_MAP_F1",                 // 241
    "UNUSED_MAP_F2",                 // 242
    "UNUSED_MAP_F3",                 // 243
    "UNUSED_MAP_F4",                 // 244
    "LORELEIS_ROOM",                 // 245
    "BRUNOS_ROOM",                   // 246
    "AGATHAS_ROOM",                  // 247
    "SUMMER_BEACH_HOUSE",            // 248
}};
} // namespace kanto
